version: '3.9'
services:
  big-honey-bot:
    container_name: big-honey-bot
    build:
      context: .
    deploy:
      restart_policy:
        condition: on-failure
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    env_file:
      - ./.env
    environment:
      - UPDATE_SIDEBAR=False
      - THREAD_STATS=True
      - IN_PLAYOFFS=False
      - PLAYOFF_WATCH=False
      - IS_OFFSEASON=True